import { useState, useRef, useEffect } from 'react';

export default function TermsAgreement({ onAccept, onReject, viewOnly = false }) {
  const scrollRef = useRef(null);
  const [showArrow, setShowArrow] = useState(true);

  useEffect(() => {
    const el = scrollRef.current;
    if (!el) return;
    function handleScroll() {
      const atBottom = el.scrollHeight - el.scrollTop - el.clientHeight < 10;
      setShowArrow(!atBottom);
    }
    el.addEventListener('scroll', handleScroll);
    handleScroll();
    return () => el.removeEventListener('scroll', handleScroll);
  }, []);

  return (
    <div className="fixed bottom-0 left-0 right-0 z-[100] animate-slide-up">
      <div className="bg-white dark:bg-gray-800 border-t-2 border-blue-500 dark:border-blue-400 shadow-[0_-8px_30px_rgba(0,0,0,0.2)] px-6 py-4">
        <div className="max-w-4xl mx-auto space-y-3">
          {/* Header */}
          <div className="flex items-center gap-2">
            <svg className="w-4 h-4 text-blue-600 dark:text-blue-400 shrink-0" fill="none" viewBox="0 0 24 24" stroke="currentColor">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 12l2 2 4-4m5.618-4.016A11.955 11.955 0 0112 2.944a11.955 11.955 0 01-8.618 3.04A12.02 12.02 0 003 9c0 5.591 3.824 10.29 9 11.622 5.176-1.332 9-6.03 9-11.622 0-1.042-.133-2.052-.382-3.016z" />
            </svg>
            <h3 className="text-sm font-bold text-gray-900 dark:text-gray-100">Terms of Service & Privacy Policy</h3>
          </div>

          {/* Content — scrollable with scroll indicator */}
          <div className="relative">
            <div ref={scrollRef} className="text-xs text-gray-600 dark:text-gray-300 leading-relaxed space-y-2 max-h-[14vh] overflow-y-auto pr-2">
              <p>By continuing to use SnapLearn, you acknowledge that you have read, understood, and agree to be bound by the following terms and conditions:</p>

              <p className="font-semibold text-gray-800 dark:text-gray-200">1. Purpose & Acceptable Use</p>
              <p>SnapLearn is an AI-powered educational tool designed to assist students in understanding academic material. You agree to use it solely for legitimate learning purposes. Any use for cheating, plagiarism, academic dishonesty, or submitting AI-generated work as your own without disclosure is strictly prohibited and may violate your school's academic integrity policy.</p>

              <p className="font-semibold text-gray-800 dark:text-gray-200">2. AI-Generated Content Disclaimer</p>
              <p>All answers, explanations, practice problems, and study recommendations are generated by OpenAI's GPT-4o model. While we strive for accuracy, AI-generated content may contain factual errors, incomplete reasoning, or outdated information. SnapLearn does not guarantee the correctness of any response. You should always cross-reference important information with your textbook, instructor, or other authoritative sources before relying on it for academic work.</p>

              <p className="font-semibold text-gray-800 dark:text-gray-200">3. Image Upload & Processing</p>
              <p>When you upload a photo, the image is transmitted securely to OpenAI's API for real-time analysis. Images are processed immediately and are not stored, cached, or retained on SnapLearn's servers or any third-party servers after processing is complete. You are responsible for ensuring that any images you upload do not contain sensitive personal information, confidential exam content that you are not authorized to share, or copyrighted material used without permission.</p>

              <p className="font-semibold text-gray-800 dark:text-gray-200">4. Authentication & Account Security</p>
              <p>SnapLearn does not have its own account system. Instead, we use Clerk (clerk.com), a trusted third-party authentication provider, to manage all user sign-in and account security. When you click "Sign in" or "Get started free", you will be redirected to a Clerk-hosted login page — this is normal and expected. You will create a Clerk account (or sign in with Google) to access SnapLearn. Your login credentials, passwords, and personal information are stored and managed entirely by Clerk, not by SnapLearn. We never have access to your password. If you encounter issues signing in (e.g. Google login not responding), try using an incognito/private browser window or check that your browser is not blocking pop-ups. You are responsible for maintaining the security of your account and should not share your login credentials with others.</p>

              <p className="font-semibold text-gray-800 dark:text-gray-200">5. Data Storage & Privacy</p>
              <p>Your study history, preferences, and session data are stored locally in your browser's localStorage. This data never leaves your device and is not transmitted to our servers. Clearing your browser data will permanently delete this information. We do not sell, share, rent, or distribute your personal data to any third parties. We may collect anonymous, aggregated usage analytics (such as feature usage counts) to improve the service, but this data cannot be used to identify individual users.</p>

              <p className="font-semibold text-gray-800 dark:text-gray-200">6. Age Requirement</p>
              <p>You must be at least 13 years of age to use SnapLearn. If you are between 13 and 18 years old, you represent that you have obtained parental or guardian consent to use this service. SnapLearn is not directed at children under 13 and we do not knowingly collect data from children under 13.</p>

              <p className="font-semibold text-gray-800 dark:text-gray-200">7. Fair Use & Rate Limiting</p>
              <p>Please use SnapLearn responsibly. Excessive, automated, or abusive usage (including but not limited to scripted requests, bulk uploads, or attempts to reverse-engineer the service) may result in temporary or permanent rate limiting or account suspension without prior notice.</p>

              <p className="font-semibold text-gray-800 dark:text-gray-200">8. Limitation of Liability</p>
              <p>SnapLearn is provided "as is" and "as available" without warranties of any kind, express or implied. We disclaim all warranties including, but not limited to, implied warranties of merchantability, fitness for a particular purpose, and non-infringement. In no event shall SnapLearn, its creators, or affiliates be liable for any direct, indirect, incidental, consequential, or punitive damages arising from your use of the service, including but not limited to poor academic performance, incorrect answers, or reliance on AI-generated content.</p>

              <p className="font-semibold text-gray-800 dark:text-gray-200">9. Changes to Terms</p>
              <p>We reserve the right to modify these terms at any time. Continued use of SnapLearn after changes are posted constitutes your acceptance of the revised terms. We encourage you to review these terms periodically.</p>
            </div>

            {/* Scroll down indicator */}
            {showArrow && (
              <div className="absolute bottom-0 left-0 right-0 flex justify-center pointer-events-none">
                <div className="bg-gradient-to-t from-white dark:from-gray-800 to-transparent w-full h-8 absolute bottom-0" />
                <div className="relative animate-bounce text-blue-500 dark:text-blue-400 mb-0.5">
                  <svg className="w-5 h-5" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M19 9l-7 7-7-7" />
                  </svg>
                </div>
              </div>
            )}
          </div>

          {/* Buttons */}
          <div className="flex items-center justify-end gap-3">
            {viewOnly ? (
              <button
                onClick={onAccept}
                className="px-7 py-2 bg-blue-600 hover:bg-blue-700 text-white text-sm font-semibold rounded-lg transition-colors cursor-pointer"
              >
                Close
              </button>
            ) : (
              <>
                <button
                  onClick={onReject}
                  className="px-7 py-2 bg-gray-200 dark:bg-gray-700 hover:bg-gray-300 dark:hover:bg-gray-600 text-gray-700 dark:text-gray-200 text-sm font-semibold rounded-lg transition-colors cursor-pointer"
                >
                  Reject
                </button>
                <button
                  onClick={onAccept}
                  className="px-7 py-2 bg-blue-600 hover:bg-blue-700 text-white text-sm font-semibold rounded-lg transition-colors cursor-pointer shadow-md shadow-blue-600/25"
                >
                  Accept
                </button>
              </>
            )}
          </div>
        </div>
      </div>
    </div>
  );
}
