import { useState } from 'react';

const TERMS_KEY = 'snaplearn_terms_accepted';

export function hasAcceptedTerms() {
  return localStorage.getItem(TERMS_KEY) === 'true';
}

export default function TermsAgreement({ onAccept, viewOnly = false }) {
  const [showFull, setShowFull] = useState(viewOnly);

  function handleAccept() {
    if (!viewOnly) localStorage.setItem(TERMS_KEY, 'true');
    onAccept();
  }

  return (
    <div className="fixed inset-0 z-[100] flex items-center justify-center bg-gray-900/60 backdrop-blur-sm p-4">
      <div className="bg-white dark:bg-gray-800 rounded-2xl shadow-2xl max-w-lg w-full overflow-hidden">
        {/* Header */}
        <div className="bg-gradient-to-br from-blue-600 to-indigo-600 px-6 py-8 text-center">
          <div className="w-14 h-14 mx-auto mb-4 rounded-2xl bg-white/20 flex items-center justify-center">
            <svg className="w-8 h-8 text-white" fill="none" viewBox="0 0 24 24" stroke="currentColor">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d="M12 6.253v13m0-13C10.832 5.477 9.246 5 7.5 5S4.168 5.477 3 6.253v13C4.168 18.477 5.754 18 7.5 18s3.332.477 4.5 1.253m0-13C13.168 5.477 14.754 5 16.5 5c1.747 0 3.332.477 4.5 1.253v13C19.832 18.477 18.247 18 16.5 18c-1.746 0-3.332.477-4.5 1.253" />
            </svg>
          </div>
          <h2 className="text-2xl font-bold text-white">{viewOnly ? 'Terms & Privacy' : 'Welcome to SnapLearn'}</h2>
          <p className="text-blue-100 text-sm mt-2">{viewOnly ? 'SnapLearn Terms of Service & Privacy Policy' : 'Please review and accept our terms to continue'}</p>
        </div>

        {/* Terms content */}
        <div className="px-6 py-5">
          <div className={`text-sm text-gray-600 dark:text-gray-300 space-y-3 overflow-y-auto ${showFull ? 'max-h-64' : 'max-h-40'} pr-2`}>
            <h3 className="font-semibold text-gray-900 dark:text-gray-100">Terms of Service</h3>
            <p>By using SnapLearn, you agree to the following terms:</p>
            <ul className="list-disc pl-5 space-y-1.5">
              <li><strong>Educational use only.</strong> SnapLearn is designed to help students learn and understand academic material. It is not intended to be used for cheating or academic dishonesty.</li>
              <li><strong>AI-generated content.</strong> Answers, explanations, and practice problems are generated by AI (GPT-4o). While we strive for accuracy, responses may contain errors. Always verify important information with your instructor or textbook.</li>
              <li><strong>Image processing.</strong> Photos you upload are sent to OpenAI for analysis. Images are processed in real time and are not stored on our servers.</li>
              <li><strong>Account data.</strong> Your study history is stored locally on your device. Clearing your browser data will remove your history.</li>
              <li><strong>Age requirement.</strong> You must be at least 13 years old to use SnapLearn, or have parental consent.</li>
              <li><strong>Fair use.</strong> Please use the service responsibly. Excessive or abusive usage may result in rate limiting.</li>
            </ul>

            {showFull && (
              <>
                <h3 className="font-semibold text-gray-900 dark:text-gray-100 pt-2">Privacy Policy</h3>
                <ul className="list-disc pl-5 space-y-1.5">
                  <li>We use Clerk for authentication. Your login information is managed securely by Clerk.</li>
                  <li>Uploaded images are sent directly to OpenAI's API for analysis and are not stored by SnapLearn.</li>
                  <li>Study history and preferences are stored in your browser's local storage only.</li>
                  <li>We do not sell, share, or distribute your personal data to third parties.</li>
                  <li>We may collect anonymous usage analytics to improve the service.</li>
                </ul>

                <h3 className="font-semibold text-gray-900 dark:text-gray-100 pt-2">Disclaimer</h3>
                <p>SnapLearn is provided "as is" without warranty of any kind. We are not responsible for any academic decisions made based on AI-generated content. Use your own judgment and consult your teachers for important academic matters.</p>
              </>
            )}
          </div>

          {!showFull && (
            <button
              onClick={() => setShowFull(true)}
              className="text-blue-600 dark:text-blue-400 text-sm font-medium mt-2 hover:text-blue-800 dark:hover:text-blue-300 cursor-pointer"
            >
              Read full terms &amp; privacy policy...
            </button>
          )}
        </div>

        {/* Button */}
        <div className="px-6 pb-6">
          <button
            onClick={handleAccept}
            className="w-full py-3 bg-blue-600 hover:bg-blue-700 text-white font-semibold rounded-xl transition-colors cursor-pointer shadow-lg shadow-blue-600/25"
          >
            {viewOnly ? 'Close' : 'I Agree & Continue'}
          </button>
          {!viewOnly && (
            <p className="text-xs text-gray-400 dark:text-gray-500 text-center mt-3">
              By clicking "I Agree &amp; Continue", you accept our Terms of Service and Privacy Policy.
            </p>
          )}
        </div>
      </div>
    </div>
  );
}
